### ISSUE TITLE
Support for the Material theme

### ISSUE THREAD

**Issue by immanuelfodor** [waschinski/shaarli-targetblank#1]
Since the plugin selects `linklist-real-url`, it doesn't work with the famous [Material theme](https://github.com/kalvn/Shaarli-Material).

Could you please adapt the code to work with it, too? (`link-url` and `link-title`)

![image](https://github.com/user-attachments/assets/980f3e89-385c-4471-a309-a6a0ef683b4f)

![image](https://github.com/user-attachments/assets/a1e491c6-9ae0-45fe-86d1-31b858d31a09)

**Comment by waschinski** [comment]
Hi, thanks for pointing this out! The latest commit 14064ca should make the plugin compatible with themes like that. I've also added a check for the `tagName` before adding the `target` attribute.

**Comment by immanuelfodor** [comment]
It works fine, thank you so much for the speedy fix! :tada:
